# Generated by Django 3.2 on 2021-05-08 05:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wardhacovidhelpapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='plasmadonars',
            options={'ordering': ['-verified']},
        ),
    ]
