# Generated by Django 3.2 on 2021-05-08 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wardhacovidhelpapp', '0002_alter_plasmadonars_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlasmaDonarsForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(blank=True, max_length=200, null=True)),
                ('Age', models.IntegerField(null=True)),
                ('Gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('other', 'other')], max_length=50)),
                ('BloodGroup', models.CharField(choices=[('O+', 'O+'), ('O-', 'O-'), ('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('Dontknow', 'Dont know')], max_length=50)),
                ('PhoneNumber', models.CharField(blank=True, max_length=10, null=True)),
                ('verified', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-verified'],
            },
        ),
        migrations.CreateModel(
            name='PlasmaRequestForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(blank=True, max_length=200, null=True)),
                ('Age', models.IntegerField(null=True)),
                ('Gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('other', 'other')], max_length=50)),
                ('BloodGroup', models.CharField(choices=[('O+', 'O+'), ('O-', 'O-'), ('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('Dontknow', 'Dont know')], max_length=50)),
                ('PhoneNumber', models.CharField(blank=True, max_length=10, null=True)),
                ('HospitalName', models.CharField(blank=True, max_length=500, null=True)),
                ('complete', models.BooleanField(default=False)),
            ],
        ),
    ]
