# Generated by Django 3.2 on 2021-05-08 11:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wardhacovidhelpapp', '0003_plasmadonarsform_plasmarequestform'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PlasmaDonarsForm',
            new_name='PlasmaDonar',
        ),
        migrations.RenameModel(
            old_name='PlasmaDonars',
            new_name='PlasmaDonarForm',
        ),
    ]
