# Generated by Django 3.2 on 2021-05-09 13:45

import datetime
from django.db import migrations, models
import django.utils.timezone
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('wardhacovidhelpapp', '0004_auto_20210508_1638'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PlasmaDonarForm',
        ),
        migrations.DeleteModel(
            name='PlasmaRequestForm',
        ),
        migrations.AlterModelOptions(
            name='plasmarequest',
            options={'ordering': ['complete']},
        ),
        migrations.AddField(
            model_name='plasmadonar',
            name='DateCreated',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Date Created'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='plasmadonar',
            name='DateOfNegative',
            field=models.DateField(default=datetime.datetime(2021, 5, 9, 13, 44, 38, 573877, tzinfo=utc), verbose_name='Date of Negative (dd/mm/yyyy)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='plasmarequest',
            name='DateCreated',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Date Created'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='plasmarequest',
            name='DateOfPositive',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Date of Positive (dd/mm/yyyy)'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='plasmadonar',
            name='Age',
            field=models.CharField(max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='plasmadonar',
            name='BloodGroup',
            field=models.CharField(choices=[('O+', 'O+'), ('O-', 'O-'), ('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('Dontknow', 'Dont know')], max_length=50, verbose_name='Blood Group'),
        ),
        migrations.AlterField(
            model_name='plasmadonar',
            name='Name',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='plasmadonar',
            name='PhoneNumber',
            field=models.CharField(max_length=10, null=True, verbose_name='Phone Number'),
        ),
        migrations.AlterField(
            model_name='plasmarequest',
            name='Age',
            field=models.CharField(max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='plasmarequest',
            name='BloodGroup',
            field=models.CharField(choices=[('O+', 'O+'), ('O-', 'O-'), ('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('Dontknow', 'Dont know')], max_length=50, verbose_name='Blood Group'),
        ),
        migrations.AlterField(
            model_name='plasmarequest',
            name='HospitalName',
            field=models.CharField(max_length=500, null=True, verbose_name='Hospital Name'),
        ),
        migrations.AlterField(
            model_name='plasmarequest',
            name='Name',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='plasmarequest',
            name='PhoneNumber',
            field=models.CharField(max_length=10, null=True, verbose_name='Phone Number'),
        ),
    ]
