# Generated by Django 3.2 on 2021-05-09 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wardhacovidhelpapp', '0005_auto_20210509_1915'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plasmadonar',
            name='DateOfNegative',
            field=models.DateField(verbose_name='Date of Negative (yyyy/mm/dd)'),
        ),
        migrations.AlterField(
            model_name='plasmarequest',
            name='DateOfPositive',
            field=models.DateField(verbose_name='Date of Positive (yyyy/mm/dd)'),
        ),
    ]
