# Generated by Django 3.2 on 2021-05-13 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wardhacovidhelpapp', '0009_plasmarequest_verified'),
    ]

    operations = [
        migrations.CreateModel(
            name='HospitalData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('HospitalName', models.CharField(max_length=300, null=True)),
                ('Address', models.TextField(max_length=300, null=True)),
                ('PhoneNumber', models.CharField(max_length=50, null=True)),
                ('Verified', models.BooleanField(default=False)),
            ],
        ),
    ]
