# Generated by Django 3.2 on 2021-05-15 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wardhacovidhelpapp', '0010_hospitaldata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teammembers',
            name='ProfileImage',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
