# Generated by Django 3.2 on 2021-05-17 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wardhacovidhelpapp', '0011_alter_teammembers_profileimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='CovidNewsPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=300, null=True)),
                ('Short_Discription', models.TextField(null=True)),
                ('Full_Description', models.TextField(null=True)),
                ('News_Image', models.ImageField(upload_to='static/newsimages')),
                ('Date_Created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
