# Generated by Django 3.2 on 2021-05-17 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wardhacovidhelpapp', '0013_auto_20210517_1552'),
    ]

    operations = [
        migrations.AlterField(
            model_name='covidnewspost',
            name='News_Image',
            field=models.ImageField(upload_to='newsimages'),
        ),
    ]
