# Generated by Django 3.2 on 2021-05-22 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wardhacovidhelpapp', '0014_alter_covidnewspost_news_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='VaccineAvailablity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=200, null=True)),
                ('AvailableCapacity', models.CharField(max_length=5, null=True)),
                ('VaccineName', models.CharField(max_length=100, null=True)),
                ('MinAgeLimit', models.CharField(max_length=3, null=True)),
                ('BlockName', models.CharField(max_length=100, null=True)),
                ('DistrictName', models.CharField(max_length=100, null=True)),
                ('FeeType', models.CharField(max_length=100, null=True)),
            ],
        ),
    ]
