# Generated by Django 3.2 on 2021-05-23 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wardhacovidhelpapp', '0016_vaccineavailablity_lastupdated'),
    ]

    operations = [
        migrations.CreateModel(
            name='Groceries',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Store_Name', models.CharField(max_length=200, null=True)),
                ('Address', models.TextField(max_length=300, null=True)),
                ('Phone_Number', models.CharField(max_length=200, null=True)),
                ('Delivery_Type', models.CharField(choices=[('Free', 'Free Delivery'), ('Paid', 'Paid Delivery')], max_length=50, null=True)),
                ('Store_Remarks', models.TextField(max_length=500, null=True)),
                ('Admin_Verified', models.BooleanField(default=False)),
            ],
        ),
    ]
