# Generated by Django 3.2 on 2021-05-23 13:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wardhacovidhelpapp', '0017_groceries'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='groceries',
            options={'verbose_name_plural': 'Groceries'},
        ),
        migrations.AlterModelOptions(
            name='hospitaldata',
            options={'verbose_name_plural': 'Hospital Data'},
        ),
        migrations.AlterModelOptions(
            name='vaccineavailablity',
            options={'verbose_name_plural': 'Vaccine Availablity'},
        ),
    ]
