# Generated by Django 3.2 on 2021-05-23 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wardhacovidhelpapp', '0018_auto_20210523_1837'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groceries',
            name='Delivery_Type',
            field=models.CharField(choices=[('Free Delivery', 'Free Delivery'), ('Paid Delivery', 'Paid Delivery')], max_length=50, null=True),
        ),
    ]
